apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-ingress
  namespace: default
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wisecow.com
      secretName: wisecow-tls
  rules:
    - host: wisecow.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wisecow-deployment
                port:
                  number: 4499
